### ISSUE TITLE
No filename for proposal PDF's

### ISSUE THREAD

**Issue by tymees** [UiL-OTS-labs/ethics#132]
From e-mail:

> Nu download ik de pdf’s van de laatste versies (20-258-03 en 20-261-03) en voorheen hadden de bestandsnamen van de pfd’s dit referentienummer, wat heel handig is, maar nu staat er niks in de bestandsnaam van 258 (die ik eerst downloade) en -1 in de naam van 261 (die ik daarna downloade). Kan dit weer teruggezet worden? Zou héél fijn zijn…

I have no idea why they are under the impression that there were filenames to begin with. While applicants get an actual file-link, the committee get the PDF through a special View which generates the PDF on the fly. This view can set a filename, but this will force the PDF to be downloaded instead of being shown in browser. (Through the ``pdf_filename`` class attribute, or the ``get_filename`` method).

This variable/method will cause the view to set the ``Content-Disposition`` header, but will always set it as an attachment.

Couple of solutions:
* Do nothing, and just tell the committee it's what it is (not preferred I guess)
* Change all references to the PDF view to a simple link for the pre-generated file
* Use the view's methods to set the filename, and accept the file will never open in browser
* Set the ``Content-Disposition`` header ourselves.

I'm fond of option 3 and 4

**Comment by tymees** [comment]
@mhkuu Do you remember why committee members get a on-the-fly generated PDF and not the pre-generated one like applicants do?

**Comment by mhkuu** [comment]
No, sorry, can't remember. Perhaps I added the field to save the PDF at a later point and didn't change the view to use this file? Indeed seems strange to regenerate the PDFs, unless we expect something to change in the Proposal (but I don't think the secretary is able to make amendments, right?)

**Comment by tymees** [comment]
Secretary is able to make some small revisions like updating consent forms, but that's about it

**Comment by miggol** [comment]
Now that our filenames are completely regular, I think it's a good idea to close off our /media/ from the world and return the right files with a FileResponse, rather than a media link. I think that's what Ty is suggesting in option 4. Inline content-disposition with a filename hint is the best of both worlds.

I'm always a fan of closing off the uploads dir for security / data / privacy reasons. but I could imagine a case where reviewers want to be able to link to a file directly to share it to the outside world. Do we have an opinion on that?

**Comment by tymees** [comment]
I agree that using a View instead of a direct media link is preferable in a security sense.

However, I don't think security or privaty is a big concern for this application. (With the exception of the committee reviews). Anything the applicant enters should not be sensitive enough to warrant strict security like that.

That being said, I do think having only one way to view the PDF is better from a technical standpoint. (It's duplicate functionality after all). 

In which case, using the View based solution is best in my opinion. It saves storage space (minor reason, but still), allows us to change the template after the fact and would make submission less likely to fail. (As any error in the PDF won't stop the submission anymore). 

On the other hand, we would not have a record of the original PDF as submitted anymore, which could be a downside. (Both in a administrative sense as well as in a technical sense. The latter meaning we have to be 100% sure we're backwards compatible in our changes in the PDF). 

So I would propose putting that idea into a different issue for further discussion, and fix the filename issue first. 

> but I could imagine a case where reviewers want to be able to link to a file directly to share it to the outside world. Do we have an opinion on that?

I don't. Let's ask Desiree!

>  I think that's what Ty is suggesting in option 4.

Yes. Although the PDF uses a special PDF-related view, not the FileResponse. Minor point, but worth mentioning as the FileResponse would handle the headers for us, but we actually need to fix the headers ourselves in this case.

I think overwriting the get method with something like this should work:

````
def get(self, *args, **kwargs)
    response = super().get(*args, **kwargs)
    response["Content-Disposition"] = "blaat"
    return response
````

**Comment by tymees** [comment]
Update:

Option 3 is probably going to be the solution. (yay 5 min fix). Desiree will bring it up at the next committee meeting, so we'll have to wait till they give the green light

**Comment by miggol** [comment]
All committee members have agreed with option 3, so this is ready to be implemented

**Comment by miggol** [comment]
The current state of this issue is that when linking to a file to be downloaded, templates include `download="{{file.name}}` in the `<a>` tag. This works adequately except for the following issue:

When the proposal changes but the file does not, for example when moving chambers or creating a revision, the file name still stays the same as at the time of uploading.

On the bright side, we are now one step closer to generating filenames on-demand. This could be done with a tag like comparison links, but I don't like having to pass an owner object on as an argument. So I'm thinking of writing a model-aware filefield with its own method for compare and filename generation. Still needs some research because it has to be migratable and such, but when Documents finally get reworked I can dig my teeth into it.

For now, I think this is reasonable place to leave this issue for the time being.
