### ISSUE TITLE
Request: hide reviews from list

### ISSUE THREAD

**Issue by miggol** [UiL-OTS-labs/ethics#186]
The reviews list can get very bogged up with reviews that are no longer active, completely abandoned, or otherwise likely to take a while to get to. It would therefore be quite handy to be able to hide reviews. 

I think the best way to proceed would be to have a per-user list of hidden reviews which can also be viewed separately. A javascript "show hidden" checkbox would be very nice, but I'm not sure how that would work with our current list views and pagination. Will look into this further.

**Comment by tymees** [comment]
First off, do we really want a 'hide' option? A 'close because it's dead (jim)' button would suffice for everything except 'otherwise likely to take a while to get to'.

It would certainly be a simpler solution as well. 

However, if we really want a hide option: 
I'm currently (still) rewriting the list views. The new solution does have filtering capabilities, which can dynamically filter out stuff. We'd only need to add a 'hidden' attribute to the data, and set a default filter to hide those away. 

I'm currently 90% done, and hope to have a PR ready sometime next week. That being said, I'm currently fighting a very annoying infinite recursion bug, so it might slip a bit.

**Comment by miggol** [comment]
> First off, do we really want a 'hide' option?

Good question. It's bound to cause frustrations such as reviewers forgetting about stuff they've hidden. A way to scrap abandoned reviews would be higher priority, so I'll look into that for the time being.

Also if the new listview has filtering and searching that would already make finding the right review a lot easier, possibly making a hide function unnecessary. Looking forward to that PR, we can evaluate a hiding feature after.

**Comment by miggol** [comment]
Covered by #198, a separate hiding feature is no longer deemed necessary.
