### ISSUE TITLE
Automatically rename uploaded files

### ISSUE THREAD

**Issue by tymees** [UiL-OTS-labs/ethics#98]
Uploaded documents should be named according to the following format:
`{refnum}-{trajectory}-{type}`, where:

* refnum, the reference number of the proposal
* trajectory, the trajectory number. (Ideally prefixed with 'trajectory'). Note: some documents are regarded as 'extra' and don't have a trajectory. In which case it should say 'extra'
* type, the type of document. This should be one of the following: 
  * IB - for 'informatiebrieven' (including for the parents)
  * TV - for 'toestemmingsformulieren`
  * IB-SL - for 'informatiebrieven schoolleiding`

You can implement this using a callable, see this documention:
https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.FileField.upload_to

Also, the documents aren't attached to the proposal directly, rather through an intermediate `Documents` model

**Comment by tymees** [comment]
(Also, please make sure the original file extension is preserved!)

**Comment by miggol** [comment]
So I had a call Desirée about this and she mentioned some additional requirements and potential improvements. 

* Add AK/LK to filename
* Remove FETC from filename (it's redundant and makes everything very long)
* It is unclear if a file has been actually added or removed in the form, therefore a separate save button would be nice.
* There should be a notice telling users that their files will be renamed
* Ideally, users should be able to annotate the filename with a single word designating what kind of (extra) document it is.
* The current implementation of extra documents is a bit weird because sometimes IB+TV are combined, notably for parents. So adding them as pairs can sometimes be confusing.

Despite all the constructive criticism, Desirée was very enthusiastic about not having to rename all the files manually all the time. However, fully automated naming has some more pitfalls:

* Every time a file is changed, i.e. overwritten by a new upload, Django sees it a as duplicate filename and appends a random string (`_o67isj.pdf`).
  * The random string is quite ugly: an incrementing number would be preferred. In particular when adding "extra" documents.
    * Overwritten files do not appear to get deleted anytime soon, so the number would keep going up.
* The original filename might contain valuable info. Even if we warn users that they will be renamed, I'm sure there will be many occasions where people have to open files again and again to make sure they uploaded the right one. (maybe that's a good thing?)

All in all this seems like way more work that I originally thought so I made a separate branch for it. I also think it's up for discussion how much of this needs to be implemented for the 3.0 milestone. Right now I want to work on the other issues and decide based on the remaining time available.

Whenever I had to engineer file uploads previously, I had the CMS rename them to a random string, keeping a reference to the original filename in the database. Filenames from then on would be generated at download-time, even if it's the exact same original filename. I always thought that was quite elegant and flexible. This also keeps user input off of the filesystem, which has security and privacy benefits. 

I'm quite tempted to do that here as well, redoing the Documents container while I'm at it. But that endeavour would require quite a bit more research on my part to do the Django way.

**Comment by tymees** [comment]
> It is unclear if a file has been actually added or removed in the form, therefore a separate save button would be nice.

Good luck implementing that... This would probably require a custom widget, which in itself isn't hard, but the FileField is weird.

Hopefully we won't need to make our own Model Field variant....

> There should be a notice telling users that their files will be renamed

Won't it actually be more confusing if we tell them? 

I don't think the researchers actually look at the filenames all that well, but saying we are going to modify their stuff might scare them. 

Anyway, should be worded carefully then...

> Ideally, users should be able to annotate the filename with a single word designating what kind of (extra) document it is.

This would definetly require a custom model field... Or a VERY complicated custom form widget. 

Alternatively, in the case of an extra document, we might want to consider refactoring that functionality a bit. For example, instead of using ``Document`` models, we could create a ``ExtraDocument`` model with a ``FileField`` and a ``TextField`` for the name. 

That won't help for the regular documents however... It would solve this however:
> The current implementation of extra documents is a bit weird because sometimes IB+TV are combined, notably for parents. So adding them as pairs can sometimes be confusing.

> Every time a file is changed, i.e. overwritten by a new upload, Django sees it a as duplicate filename and appends a random string (_o67isj.pdf). 

Adding the reference number and the trajectory number should solve this right? Or does it still happen when a file is replaced in the same proposal and trajectory?

> Whenever I had to engineer file uploads previously, I had the CMS rename them to a random string, keeping a reference to the original filename in the database. Filenames from then on would be generated at download-time, even if it's the exact same original filename. I always thought that was quite elegant and flexible. This also keeps user input off of the filesystem, which has security and privacy benefits.
>
> I'm quite tempted to do that here as well, redoing the Documents container while I'm at it. But that endeavour would require quite a bit more research on my part to do the Django way.

Completely agree with this, it is a better approach. (And one I also use when I have to write stuff like this from scratch). However, it's not the way Django likes to do things, so this would entail writing a custom FileField implementation...

Which I have been repeating a lot in this comment, so we might actually want to do that! However, that would entail making a migration strategy, so we would have discuss this in more detail. 

So for now, I think it might be best to make a simple stop-gap solution. If we have time before the end of the month to create such a solution, that would be great. However, I don't think that this will be the case, so we might want to keep this idea for version 3.1. (The Django 2.2 update being version 3.0)
